name: Build Spotify2MP3 for Universal2 macs

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create'
        default: '1.3.4'
        required: true
        type: string

env:
  LEVEL: ${{ inputs.version }}

jobs: 
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Install dependencies
      run: |
        # Install system dependencies
        brew install python-tk@3.13
        brew install tcl-tk
        
        # Install Python dependencies with Universal2 support
        python3 -m pip install --upgrade pip
        # Force pip to install universal2 wheels when available
        export PIP_EXTRA_INDEX_URL="https://pypi.org/simple"
        export PIP_PREFER_BINARY=1
        # Install all requirements with universal2 support
        ARCHFLAGS="-arch arm64 -arch x86_64" python3 -m pip install -r requirements.txt --no-cache-dir

    - name: Download and setup ffmpeg
      run: |
        mkdir -p ffmpeg
        cd ffmpeg
        curl -L https://evermeet.cx/ffmpeg/ffmpeg-7.1.1.7z -o ffmpeg.7z
        tar -xvf ffmpeg.7z
        rm -rf ffmpeg.7z

    - name: Download and setup yt-dlp
      run: |
        mkdir -p yt-dlp
        cd yt-dlp
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos -o yt-dlp
        chmod +x yt-dlp
        
    - name: Build with PyInstaller and create zip file
      run: |
        # Set architecture flags for PyInstaller
        export ARCHFLAGS="-arch arm64 -arch x86_64"
        # Ensure Tkinter is properly linked
        export TCL_LIBRARY="/usr/local/opt/tcl-tk/lib"
        export TK_LIBRARY="/usr/local/opt/tcl-tk/lib"
        # Set Python to build universal2 binaries
        export PYTHON_CONFIGURE_OPTS="--enable-framework --with-universal-archs=intel-64"
        python3 -m PyInstaller Spotify2MP3-Universal2-macOS.spec -y --clean --log-level DEBUG
        cd dist
        ditto -c -k --keepParent "Spotify2MP3.app" Spotify2MP3_macOS_Universal2.zip

    - name: Create GitHub Draft
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.LEVEL }}
        name: Spotify2MP3 v${{ env.LEVEL }}
        draft: true
        prerelease: false
        files: |
          dist/Spotify2MP3_macOS_Universal2.zip