name: Build Spotify2MP3

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create'
        default: '1.1.1'
        required: true
        type: string

env:
  LEVEL: ${{ inputs.version }}

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --windowed --name "Spotify2MP3" \
          --add-data "ffmpeg:ffmpeg" \
          --add-data "yt-dlp:yt-dlp" \
          --add-data "config.json:." \
          spotify2media.py
        
    - name: Create GitHub Draft
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.LEVEL }}
        name: Spotify2MP3 v${{ env.LEVEL }}
        draft: true
        prerelease: false
        files: dist/Spotify2MP3.app
