name: Build Spotify2MP3 for Universal2 macs

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create'
        default: '1.3.4'
        required: true
        type: string

env:
  LEVEL: ${{ inputs.version }}

jobs: 
  build-macos:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Download and setup ffmpeg
      run: |
        mkdir -p ffmpeg
        cd ffmpeg
        curl -L https://evermeet.cx/ffmpeg/ffmpeg-7.1.1.7z -o ffmpeg.7z
        tar -xvf ffmpeg.7z
        rm -rf ffmpeg.7z

    - name: Download and setup yt-dlp
      run: |
        mkdir -p yt-dlp
        cd yt-dlp
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos -o yt-dlp
        chmod +x yt-dlp
        
    - name: Install dependencies
      run: |
          brew install pyenv
          python3 -m pip install --upgrade pip setuptools wheel
          export ARCHFLAGS="-arch x86_64 -arch arm64"
          rustup target add x86_64-apple-darwin
          pip install --no-binary=:all: -r requirements.txt
          pyinstaller Spotify2MP3-macOS.spec  --clean -y --log-level DEBUG
          cd dist
          ditto -c -k --keepParent "Spotify2MP3.app" Spotify2MP3_macOS_Universal2.zip

    - name: Create GitHub Draft
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.LEVEL }}
        name: Spotify2MP3 v${{ env.LEVEL }}
        draft: true
        prerelease: false
        files: |
          dist/Spotify2MP3_macOS_Universal2.zip